### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by callmestu** [SeisoLLC/easy_infra#147]
1. Define environment/input variables for logging with fluent-bit
2. Define config for logging with fluent-bit

Instead of making this a md file in the repo, can you put this in Wrike or a GitHub issue?

_Originally posted by @JonZeolla in https://github.com/SeisoLLC/easy_infra/pull/138#discussion_r806909601_

**Comment by JonZeolla** [comment]
Replaced by https://github.com/SeisoLLC/easy_infra/issues/148
