### ISSUE TITLE
Add logging configuration options to the GitHub Action

### ISSUE THREAD

**Issue by JonZeolla** [SeisoLLC/easy_infra#148]
Add logging configuration options to the GitHub Action using Environment, Repository, and Organization secrets, and any other logging configuration options via `fluent-bit`.

**Comment by JonZeolla** [comment]
@callmestu / @digeseiso please move this issue to the new GitHub Action repo, once it is released, and then close this with a link to the new issue

**Comment by callmestu** [comment]
Replaced by: https://github.com/SeisoLLC/deploy_infra/issues/1#issue-1183441800
