### ISSUE TITLE
Document a use case for each primary tool

### ISSUE THREAD

**Issue by JonZeolla** [SeisoLLC/easy_infra#26]
- [ ] `awscli` example.
  - [ ] `az` example.
  - [ ] `packer` example.
  - [x] `terraform` example, including `tfenv` and caching.
  - [x] `ansible` example.

**Comment by tpears** [comment]
Will start by adding sphinx and support for readthedocs.io

**Comment by JonZeolla** [comment]
Documentation is in place for all currently supported tools.  As new security controls get added, they should be documented
